### PR TITLE
add --wait=http which runs connect as soon as box is active

### PR DESCRIPTION
**Pull request by CampGareth**
This changes the --wait flag from a bool to a string on deployments specifically. When `--wait=http` is specified during `reco deployment run` reco waits for the deployment to become active, then runs `connect` and opens your web browser pointed at the instance. Unfortunately connect doesn't check the instance is listening on port 80, it just waits for an IP address, but close enough.

### CODE REVIEW

**Comment by CampGareth** [comment]
[--wait=http wait for deployment to respond on port 80](https://trello.com/c/dlEBCpuI/103-waithttp-wait-for-deployment-to-respond-on-port-80)

**Comment by CampGareth** [comment]
[Add option to reco to start and wait for port 80 to open before returning (service activation). Use for web-md5 example.](https://trello.com/c/pyxAcCcK/126-add-option-to-reco-to-start-and-wait-for-port-80-to-open-before-returning-service-activation-use-for-web-md5-example)

**Comment by robtaylor** [comment]
Probably better using net.Dial to test for port 80 up: https://golang.org/pkg/net/

Also, opening user’s browser maybe a bit overkill..

**Comment by CampGareth** [comment]
@robtaylor feature added, connect will now attempt to open a connection to port 80 repeatedly.

**Comment by CampGareth** [comment]
realised this should tell the user when it's waiting for the deployment to start and when it's waiting for port 80 to respond. Will add.

**Comment by CampGareth** [comment]
Output looks like this:
```
2018-01-05 10:37:59| Waiting for deployment to listen on port 80
2018-01-05 10:38:00| Deployment ready at http://54.209.29.74/
```

**Comment by robtaylor** [comment]
as noted in chat, now missing a bunch of info on what you're currently waiting for..

**Comment by CampGareth** [comment]
[Reco v0.4.0](https://trello.com/c/uXqkuA9Y/106-reco-v040)

**Comment by CampGareth** [comment]
@robtaylor output now looks like this:
```
$ reco deployment run --wait=true b39e6d85-4428-4ae3-9fa0-3e56f03c4982 timeout 5m run-webserver
2018-01-08 12:10:30| creating deployment
2018-01-08 12:10:31| done. Deployment id: ce31d6d0-7d16-45a8-b728-7949362a6dc1
2018-01-08 12:10:31| you can run "reco deployment log ce31d6d0-7d16-45a8-b728-7949362a6dc1" to manually stream logs
2018-01-08 12:10:32| status: SUBMITTED
2018-01-08 12:10:32| Waiting for Spot Instance Request to be created
2018-01-08 12:10:42| status: QUEUED
2018-01-08 12:10:42| Waiting for EC2 instance to be allocated
2018-01-08 12:12:54| status: STARTED
[logs from deployment]
ce31d6d0-7d16-45a8-b728-7949362a6dc1
```

That look okay to you?

**Comment by robtaylor** [comment]
Looks great for now.

**Pull request merged**
